services:
  # Backend Symfony
  - type: web
    name: blog-symfony-api
    env: php
    rootDir: blog_app
    buildCommand: composer install --no-dev --optimize-autoloader && php bin/console cache:clear --env=prod
    startCommand: php -S 0.0.0.0:$PORT -t public
    envVars:
      - key: APP_ENV
        value: prod
      - key: DATABASE_URL
        value: postgresql://postgres.csuwkabbahsyqwvwomzx:Roujielbaba&2025@aws-1-eu-west-3.pooler.supabase.com:6543/postgres

  # Frontend Vue.js  
  - type: web
    name: blog-vue-frontend
    env: static
    rootDir: mon-slider-vue
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: VITE_API_URL
        value: https://blog-symfony-api.onrender.com